steps:

- name: 'gcr.io/cloud-builders/docker'

  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app', '.']
 
serviceAccount: projects/PROJECT_ID/serviceAccounts/your-sa@project.iam.gserviceaccount.com
 
options:

  logging: CLOUD_LOGGING_ONLY
 