steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp', '.']
 
images:
  - 'gcr.io/$PROJECT_ID/myapp'
 
serviceAccount: 'your-service-account@your-project.iam.gserviceaccount.com'
 
options:
  logging: CLOUD_LOGGING_ONLY